import { style } from 'components/Policies/styles'

const HIPAA = () => (
  <>
    <h3 css={style.tabContent.title}>HIPAA Notice of Privacy Practices</h3>
    <span css={style.tabContent.date}>Last updated: 03/18/2021</span>
    <p css={style.tabContent.text}>
    Notice of Privacy Practices
    </p>
    <p css={style.tabContent.text}>
    THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU OR YOUR CHILD MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.WE KEEP A RECORD OF THE HEALTH CARE SERVICES WE PROVIDE YOU. YOU MAY ASK US TO SEE AND COPY THAT RECORD. YOU MAY ALSO ASK US TO CORRECT THAT RECORD. WE WILL NOT DISCLOSE YOUR RECORD TO OTHERS UNLESS YOU DIRECT US TO DO SO OR UNLESS THE LAW AUTHORIZES OR COMPELS US TO DO SO. YOU MAY SEE YOUR RECORD OR GET MORE INFORMATION ABOUT IT BY CONTACTING PBS’S PRIVACY OFFICER AT THE ADDRESS LISTED IN SECTION IV BELOW.PBS is dedicated to maintaining the privacy of our Clients’ individually identifiable health information (also called protected health information, or PHI). In conducting our business, we will create records regarding the Client and the treatment and services we provide. We are required by law to maintain the confidentiality of health information that identifies Clients. We also are required by law to provide this notice of our legal duties and the privacy practices that we maintain in our practice concerning Client’s PHI. By federal and state law, we must follow the terms of the Notice of Privacy Practices that we have in effect at the time.
    </p>
    <p css={style.tabContent.text}>We realize that these laws are complicated, but we must provide you with the following important information:
How we may use and disclose a Client’s PHI
Privacy rights in PHI
Our obligations concerning the use and disclosure of PHI</p>
    <p css={style.tabContent.text}>The terms of this notice apply to all records containing a Client’s PHI that are created or retained by PBS. We reserve the right to revise or amend this Notice of Privacy Practices. Any revision or amendment to this notice will be effective for all our records created or maintained in the past, and for any records that we may create or maintain in the future. PBS will post a copy of our current Notice in our offices in a visible location at all times, and you may request a copy of our most current Notice at any time.</p>
    <p css={style.tabContent.text}><strong>I. HOW PBS WILL USE AND DISCLOSE PHI.</strong> PBS may use and disclose a Client’s PHI for many different reasons. Some of the uses or disclosures will require your prior written authorization; others, however, will not. Below you will find the different categories of our uses and disclosures, with some examples.
Uses and Disclosures Related to Treatment, Payment, or Health Care Operations Do Not Require Prior Written Consent. PBS may use and disclose a Client’s PHI without consent for the following reasons:
For treatment. PBS may disclose PHI to physicians, psychiatrists, psychologists, behavior interventionists and other licensed health care providers who provide a Client with health care services or are otherwise involved in his or her care. Example: If a psychiatrist is treating a Client, PBS may disclose PHI to her/him in order to coordinate services.
For health care operations. PBS may disclose PHI to facilitate the efficient and correct operation of the services it provides. Examples: Quality control - PBS might use PHI in the evaluation of the quality of services that a Client receives or to evaluate the performance of the Behavior Interventionists who provided these services. PBS may also provide PHI to company attorneys, accountants, consultants, and others to make sure that PBS is in compliance with applicable laws.
To obtain payment for treatment. PBS may use and disclose PHI to bill and collect payment for the treatment and services PBS provided.
Example: We might send PHI to the Client’s Regional Center or insurance company in order to get payment for the services that PBS has provided. PBS could also provide PHI to business associates that provide services for PBS.
Certain Other Uses and Disclosures Do Not Require Consent. PBS may use and/or disclose PHI without consent or authorization for the following reasons:
Required By Law. When disclosure is (a) required by federal, state, or local law; judicial, board, or administrative proceedings; or, law enforcement; (b) compelled by a party to a proceeding before a court, arbitration panel or an administrative agency pursuant to its lawful authority; (c) required by a search warrant lawfully issued to a governmental law enforcement agency; or (d) compelled by the patient or the patient’s representative pursuant to state or federal statutes of regulations, such as the Privacy Rule that requires this Notice.
To avoid harm. When disclosure: (a) to law enforcement personnel or persons may be able to prevent or mitigate a serious threat to the health or safety of a person or the public; (b) is compelled or permitted by the fact that the Client is in such mental or emotional condition as to be dangerous to him or herself or the person or property of others, and if PBS determines that disclosure is necessary to prevent the threatened danger; (c) is mandated by state child abuse and neglect reporting laws (for example, if we have a reasonable suspicion of child abuse or neglect); (d) is mandated by state elder/dependent abuse reporting law (for example, if we have a reasonable suspicion of elder abuse or dependent adult abuse); and (e) if disclosure is compelled or permitted by the fact that you or your child tells us of a serious/imminent threat of physical violence against a reasonably identifiable victim or victims.
For public health activities. When disclosure is for: (a) maintaining vital records, such as births and deaths; (b) preventing or controlling disease, injury or disability, (c) notifying a person regarding potential exposure to a communicable disease; (d) notifying a person regarding a potential risk for spreading or contracting a disease or condition; (d) reporting reactions to drugs or problems with products or devices; or (e) notifying individuals if a product or device they may be using has been recalled.
For health oversight activities. PBS may disclose PHI to a health oversight agency for activities authorized by law. Oversight activities can include, for example, investigations, inspections, audits, surveys, licensure and disciplinary actions; civil, administrative and criminal procedures or actions; or other activities necessary for the government to monitor government programs, compliance with civil rights laws and the health care system in general.
For specific government functions. Examples: PBS may disclose PHI of military personnel and veterans under certain circumstances.
For Workers' Compensation purposes. PBS may provide PHI in order to comply with Workers' Compensation laws.
Appointment reminders and health related benefits or services. PBS is permitted to contact you, without prior authorization, to provide appointment reminders or information about alternative or other health-related benefits and services that may be of interest.
Certain Uses and Disclosures Require You to Have the Opportunity to Object.
Disclosures to family, friends, or others. PBS may provide PHI to a family member, friend, or other individual who you indicate is involved in the Client’s care or responsible for the payment of health care, unless you object in whole or in part. Retroactive consent may be obtained in emergency situations.
Other Uses and Disclosures Require Your Prior Written Authorization. The following uses and disclosures will only be made if PBS has obtained written authorization from the Client or the Client’s parent or guardian: uses and disclosures for marketing purposes; uses and disclosures that constitute the sale of PHI; most uses and disclosures of psychotherapy notes; and other uses and disclosures not described in this Notice.
Therapy Notes: PBS keeps “therapy notes”, also referred to as progress notes.. Any use or disclosure of such notes requires your authorization unless the use or disclosure is:
For our use in treating you.
For our use in training or supervising other mental health practitioners to help them improve their skills in group, joint, family, or individual counseling or therapy.
For our use in defending myself in legal proceedings instituted by you.
For use by the Secretary of Health and Human Services to investigate our compliance with HIPAA.
Required by law, and the use or disclosure is limited to the requirements of such law.
Required by law for certain health oversight activities pertaining to the originator of the psychotherapy notes.
Required by a coroner who is performing duties authorized by law.
Required to help avert a serious threat to the health and safety of others.
PBS will not sell or disclose any PHI for marketing purposes.
PBS will not disclose your information, including PHI, for fundraising purposes.</p>
<p css={style.tabContent.text}>
<strong>II. RIGHTS REGARDING PHI.</strong> These are your rights with respect to PHI:
The Right to See and Get Copies of PHI. In general, you have the right to see PHI that is in PBS’s possession, or to get copies of it; however, you must request it in writing. PBS will provide access to the PHI within five (5) days of receipt of the written request. If PBS does not have the PHI, but PBS knows who does, PBS will advise you how you can get it. You will receive a response from PBS within 5 days of receipt of your written request. Under certain circumstances, PBS may deny your request, but PBS will give you, in writing, the reasons for the denial. PBS will also explain your right to have the denial reviewed. If you ask for copies of PHI, PBS will charge you a reasonable fee, not to exceed $0.25 per page.  PBS will provide copies of PHI within fifteen (15) days of receipt of the request.  PBS may elect to provide you with a summary or explanation of the PHI, but only if you agree to it, as well as to the cost, in advance.
The Right to Request Limits on Uses and Disclosures of PHI. You have the right to ask that PBS limit how it uses and discloses PHI. While PBS will consider your request, PBS is not legally bound to agree. If PBS does agree to your request, PBS will put those limits in writing and abide by them except in emergency situations. You do not have the right to limit the uses and disclosures that PBS is legally required or permitted to make. You have the right to restrict PBS’s disclosure of PHI to health plans if you (or a third party on your behalf) has paid for the services out of pocket and in full.
The Right to Choose How PBS Sends PHI to You. It is your right to ask that PHI be sent to you at an alternate address (for example, sending information to your work address rather than your home address) or by an alternate method (for example, via email instead of by regular mail). PBS is obliged to agree to your request providing that PBS can give you the PHI, in the format you requested, as long as the format is readily producible.
The Right to Get a List of the Disclosures PBS Has Made. You are entitled to a list of disclosures of PHI that PBS has made. The list will not include uses or disclosures to which you have already consented, i.e., those for treatment, payment, or health care operations, sent directly to you, or to your family; neither will the list include disclosures made for national security purposes, to corrections or law enforcement personnel, or disclosures made before April 15, 2003. After April 15, 2003, disclosure records will be held for six years. PBS will respond to your request for an accounting of disclosures within 60 days of receiving your request. The list PBS gives you will include disclosures made in the previous six years (the first six year period being 2003-2009) unless you indicate a shorter period. The list will include the date of the disclosure, to whom PHI was disclosed (including their address, if known), a description of the information disclosed, and the reason for the disclosure. PBS will provide the list to you at no cost, unless you make more than one request in the same year, in which case PBS will charge you a reasonable sum based on a set fee for each additional request.
The Right to Amend Your PHI. If you believe that there is some error in your PHI or that important information has been omitted, it is your right to request that PBS correct the existing information or add the missing information. Your request and the reason for the request must be made in writing. You will receive a response within ten (10) days of my receipt of your request. PBS may deny your request, in writing, if PBS finds that: the PHI is (a) correct and complete, (b) forbidden to be disclosed, (c) not part of my records, or (d) written by someone other than PBS. The denial must be in writing and must state the reasons for the denial. It must also explain your right to file a written statement objecting to the denial. If you do not file a written objection, you still have the right to ask that your request and my denial be attached to any future disclosures of your PHI. If PBS approves your request, PBS will make the change(s) to your PHI. Additionally, PBS will tell you that the changes have been made, and PBS will advise all others who need to know about the change(s) to your PHI.
The Right to Receive Breach Notification.  You have a right to receive notice in the event that your PHI is acquired, accessed, used, or disclosed in a manner not permitted by law which compromises the security or privacy of the PHI. This includes your right to be notified following a data breach.
The Right to Get This Notice by Email.  You have the right to get this notice by email or to obtain a paper copy.
</p>
<p css={style.tabContent.text}>
<strong>III. PHI Breaches.</strong> PBS shall notify clients/families by providing notice in written form by first-class mail, or alternatively, by e-mail if the affected client has agreed to receive such notices electronically. PBS may also post the notice on the home page of its web site for at least 90 days or by providing the notice in major print. PBS will provide a toll-free phone number that remains active for at least 90 days where individuals can learn if their information was involved in the breach. PBS clients/families that may have insufficient or out-of-date contact information shall be provided substitute notice by an alternative form of written notice, by telephone, or other means.
</p>
<p css={style.tabContent.text}>
<strong>IV. HOW TO COMPLAIN ABOUT PBS PRIVACY PRACTICES.</strong> If, in your opinion, PBS may have violated the Client’s privacy rights, or if you object to a decision PBS made about access to PHI, you are entitled to file a complaint with the person listed in Section IV below. You may also send a written complaint to the Office for Civil Rights, Secretary of the Department of Health and Human Services at 200 Independence Avenue S.W. Washington, D.C. 20201. If you file a complaint about PBS’s privacy practices, PBS will take no retaliatory action against you. PBS HIPAA Compliance Officer contact information: Theresa L. Wyres/Director of Quality of Assurance at 1-855-832-6727 Ext. 1011.
</p>
<p css={style.tabContent.text}>
<strong>V. PERSON TO CONTACT FOR INFORMATION ABOUT THIS NOTICE OR TO COMPLAIN ABOUT PBS’S PRIVACY PRACTICES.</strong> If you have any questions about this notice or any complaints about PBS’s privacy practices, or would like to know how to file a complaint with the Secretary of the Department of Health and Human Services, please contact us at: Positive Behavior Supports Corporation, 7108 S Kanner Hwy, Stuart FL 34997 Phone: 1-855-832-6727 Ext. 1011, <a css={style.tabContent.link} href="mailto:twyres@teampbs.com">twyres@teampbs.com</a>.
</p>
<p css={style.tabContent.text}>
<strong>VI. EFFECTIVE DATE OF THIS NOTICE OF PRIVACY PRACTICES.</strong> This Notice of Privacy Practice became effective as of January 1st, 2014 and has been updated as of July 28th, 2020. PBS will abide by and may change the terms of this Notice at any time. PBS may, at its discretion, make the new terms effective for all PHI in our possession, including any PHI created or received before the new Notice is issued via email.
</p>

  </>
)

export default HIPAA