import { formatDate } from 'Helpers/helpers'

export const counties = [
  '',
  'Alachua',
  'Baker',
  'Bay',
  'Clay',
  'Columbia',
  'Duval',
  'Alachua',
]

export const acronyms = [
  '',
  'AK',
  'Al',
  'AR',
  'AZ',
  'CA',
  'CO',
  'CT',
  'DC',
  'DE',
  'FL',
  'GA',
  'HI',
  'IA',
  'ID',
  'IL',
  'IN',
  'KS',
  'KY',
  'LA',
  'MA',
  'MD',
  'ME',
  'MI',
  'MN',
  'MO',
  'MS',
  'MT',
  'NC',
  'ND',
  'NE',
  'NH',
  'NJ',
  'NM',
  'NV',
  'NY',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VA',
  'VT',
  'WA',
  'WI',
  'WV',
  'WY',
]

export const field_list = [
  { label: 'First Name', id: 'firstName' },
  { label: 'M.I.', id: 'MI', width: '33%', maxLength: 1 },
  { label: 'Last Name', id: 'lastName' },
  { label: 'Qualification Type', id: 'qualification' },
  { label: 'Date of Birth', id: 'date_birth', type: 'date', width: '33%' },
  {
    label: 'Date of application',
    id: 'date_app',
    width: '33%',
    disabled: true,
    value: formatDate,
  },
  { label: 'Street Address', id: 'street' },
  { label: 'Apartment/Unit #', id: 'unit', width: '33%' },
  { label: 'City', id: 'city', width: '33%' },
  { label: 'ZIP', id: 'zip', placeholder: 'XXXXX', width: '13%', maxLength: 5 },
  { label: 'State', id: 'state', width: '33%', select: true, list: acronyms },
  { label: 'County', id: 'county', width: '33%', select: true, list: counties  },
  {
    label: 'Mobile Phone',
    id: 'phone',
    type: 'number',
    placeholder: '(XXX) XXX-XXXX',
    width: '33%',
    maxLength: 17,
  },
]

export const field_list_last_two = [
  { label: 'Email Address', id: 'email', type: 'email' },
  { label: 'Date Available', id: 'available', type: 'date', width: '33%' },
]

export const week_days = [
  'Times',
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
]

export const degrees = [
  'None',
  'EdD',
  'PsyD',
  'Med',
  'MSd',
  'MSSW',
  'MSW',
  'MS',
  'MA',
  'PhD',
  'Bachelor',
  'High School/GED',
]

export const refInputs = [
  { label: 'Full Name', id: 'name', half: false, placeholder: '' },
  { label: 'Relationship', id: 'relationship', half: false, placeholder: '' },
  { label: 'Company', id: 'company', half: false, placeholder: '' },
  { label: 'Phone', id: 'phone', half: true, placeholder: '(XXX)XXX-XXX' },
  { label: 'Address', id: 'address', half: false, placeholder: '' },
]

export const appointments = [
  '06:00 - 06:30 AM',
  '06:30 - 07:00 AM',
  '07:00 - 07:30 AM',
  '07:30 - 08:00 AM',
  '08:00 - 08:30 AM',
  '08:30 - 09:00 AM',
  '09:00 - 09:30 AM',
  '09:30 - 10:00 AM',
  '10:00 - 10:30 AM',
  '10:30 - 11:00 AM',
  '11:00 - 11:30 AM',
  '11:30 - 12:00 AM',
  '12:00 - 12:30 PM',
  '12:30 - 01:00 PM',
  '01:00 - 01:30 PM',
  '01:30 - 02:00 PM',
  '02:00 - 02:30 PM',
  '02:30 - 03:00 PM',
  '03:00 - 03:30 PM',
  '03:30 - 04:00 PM',
  '04:00 - 04:30 PM',
  '04:30 - 05:00 PM',
  '05:00 - 05:30 PM',
  '05:30 - 06:00 PM',
  '06:00 - 06:30 PM',
  '06:30 - 07:00 PM',
  '07:00 - 07:30 PM',
  '07:30 - 08:00 PM',
  '08:00 - 08:30 PM',
  '08:30 - 09:00 PM',
  '09:00 - 09:30 PM',
  '09:30 - 10:00 PM',
  '10:00 - 10:30 PM',
  '10:30 - 11:00 PM',
  '11:00 - 11:30 PM',
  '11:30 - 12:00 PM',
]